import "@styles/globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body suppressHydrationWarning={true}
        style={{ 
          backgroundImage: "url('/assets/images/desktopParticles.png')", 
          backgroundSize: 'cover', 
          backgroundPosition: 'center',
          backgroundColor: 'rgba(255, 255, 255, 0.9)' 
        }}
      >
        <main 
          className='app'
        >
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
