import "@styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <main className='app'>
          {/* nav bar here */}
          {children}
          {/* footer here */}
        </main>
      </body>
    </html>
  );
}
